name = "AtomicUnits"
uuid = "490ed623-4b6c-45fe-a125-b26518be62f4"
authors = ["Takuma Teramura <=> and contributors"]
version = "0.1.3"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"

[compat]
PhysicalConstants = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
